<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>7</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>9be2eb1e-b88c-45c0-884c-ae842bf2075e</testSuiteGuid>
   <testCaseLink>
      <guid>35b35683-5d0f-408a-8a8d-f67ba90d29b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo Tests/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>db3356ae-3118-4a85-a7db-e0ae92eb730e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>db3356ae-3118-4a85-a7db-e0ae92eb730e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>a9007c2c-998b-47f1-8d9c-20ed67ec32af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>db3356ae-3118-4a85-a7db-e0ae92eb730e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>726be324-aca7-474c-8f35-1dc49ea335f5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
