<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Package</name>
   <tag></tag>
   <elementGuidId>95aff417-64a2-4f59-a7a9-e87aa6348f90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Package' or . = 'Package')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='navbar-top-firstrow']/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ae07d38f-fe40-4fde-a73b-f128de0c9d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Package</value>
      <webElementGuid>797196c8-d7f8-46ab-a55b-c2d9fe17bde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-top-firstrow&quot;)/li[2]</value>
      <webElementGuid>0f1692bb-c4f9-4dad-b3eb-a2a133410402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='navbar-top-firstrow']/li[2]</value>
      <webElementGuid>59f0a29c-033c-4cf4-b0c4-00ddb07d6632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[2]/following::li[1]</value>
      <webElementGuid>2554805c-f38d-407c-804c-954eef46af36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip navigation links'])[1]/following::li[2]</value>
      <webElementGuid>ab5d4e21-b0e0-42b6-9630-6a370e6658f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class'])[1]/preceding::li[1]</value>
      <webElementGuid>5c4b0ce0-3416-4b35-9232-eeb651947396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use'])[1]/preceding::li[2]</value>
      <webElementGuid>8caa1d2e-dd2e-47c8-b01b-05804f4c8c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Package']/parent::*</value>
      <webElementGuid>939387c5-052e-4f71-958b-3d8fd07a4d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>2b75b645-328c-429d-8b20-0378fa7dd436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Package' or . = 'Package')]</value>
      <webElementGuid>1438a7bd-3027-4af0-a455-c886a48d5ada</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
